#' Package: Gene-Specific Phenotype EstimatoR
#' 
#' This package provides a model to deconvolute off-target confounded RNAi knockdown phentypes, and
#' methods to investigate concordance between ranked lists of (estimated) phenotypes. The regularized
#' linear regression model can be fitted using two different strategies. (a) Cross-validation over
#' regularization parameters optimising the mean-squared-error of the model and (b) stability selection
#' of covariates (genes) based on a method by Nicolai Meinshausen et al.
#' @name gespeR-package
#' @rdname gespeR-package
#' @aliases gespeRpkg
#' @author Fabian Schmich | Computational Biology Group, ETH ZURICH | \email{fabian.schmich@@bsse.ethz.ch}
#' @example inst/example/gespeR-example.R
#' @docType package
#' @keywords package
#' @references Fabian Schmich et. al, Deconvoluting Off-Target Confounded RNA Interference Screens (2014).
#' @import methods Matrix glmnet dplyr
#' @importFrom graphics plot
#' @seealso \code{\link{gespeR}}
NA

#' Example data: Simulated phenotypes and target relations for 4 screens (A, B, C, D)
#' 
#' The data set contains simulated data for four screens. Each screen consists of a phenotype vector
#' and target relations between siRNAs and genes, i.e. which siRNA binds which genes (on- and off-targets).
#' The size of each simulated screen is N = 1000 siRNAs x p = 1500 genes. 
#' SSPs are generated by first defining GSPs and multiplying the true GSPs with the sampled targe trelation
#' matrices. For sampling the GSPs, we set the number of effect genes to 5% and its effect strengths are sampled 
#' from Normal(0, 3).
#' Target relation matrices are simulated by sampling the number of off-targets per siRNA from 
#' Normal(3e-2 * N, 3e-3 * N) and the strength of off-targets is sampled from Beta(2, 5). On-target
#' components are set to 0.75.
#' 
#' The code used to simluate the data can be found in system.file("example", "data_simulation.R", package="gespeR")
#' 
#' @docType data
#' @examples 
#' pheno.a <- Phenotypes(system.file("extdata", "Phenotypes_screen_A.txt", package="gespeR"),
#' type = "SSP", col.id = 1, col.score = 2)
#' targets.a <- TargetRelations(system.file("extdata", "TR_screen_A.rds", package="gespeR"))
#' @name simData
NA

#' Example fits for phenotypes from simulated screening data A, B, C and D
#' 
#' The data set contains four fitted gespeR models using stability selection
#' from the four simulated screens.
#' @docType data
#' @examples data(stabilityfits)
#' @name stabilityfits
NA